[db_migrator] Remove import of swsssdk as it is not supported in master (#2544)
Fixes: sonic-net/sonic-buildimage#12955

The cherrypick changes (from 202012 to master) made as part of #2515
broke the master branch db_migrator. The issue is due to an import of swsssdk which is no longer available in master image.

How I did it
Removed the import statement that came due to cherrypick.

How to verify it
Checked on physical device running master image

Without fix:

root@str2-acs-12:~# db_migrator.py
Traceback (most recent call last):
  File "/usr/local/bin/db_migrator.py", line 11, in <module>
    from swsssdk import ConfigDBConnector, SonicDBConfig
ModuleNotFoundError: No module named 'swsssdk'
root@str2-acs-12:~# 

With fix:

root@str2-acs-12:~# db_migrator.py     
version_4_0_0
root@str2-acs-12:~#