fix radius error on unicode name error due to python3 (#2751)
fixes https://github.com/sonic-net/sonic-buildimage/issues/14356

#### What I did
fix radius command python config file for commands that fails with tracebacks due to NameError: name 'unicode' is not define

#### How I did it
delete any unicode from python config file

#### How to verify it
run the two radius commands:

```
config radius nasip 1.1.1.1
config radius sourceip 2000::1
```

and check show radius output
```
show radius
```

#### Previous command output (if the output of a command-line utility has changed)
```
root@qa-eth-vt03-1-4600ca1:/home/admin# config radius nasip 1.1.1.1
Traceback (most recent call last):
File "/usr/local/bin/config", line 8, in
sys.exit(config())
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 764, in call
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 717, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1137, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 956, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 555, in invoke
return callback(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/config/aaa.py", line 448, in nasip
v6_invalid_list = [ipaddress.IPv6Address(unicode('0::0')), ipaddress.IPv6Address(unicode('0::1'))]
NameError: name 'unicode' is not defined
root@qa-eth-vt03-1-4600ca1:/home/admin# config radius sourceip 2000::1
...
File "/usr/local/lib/python3.9/dist-packages/click/decorators.py", line 17, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/config/aaa.py", line 407, in sourceip
v6_invalid_list = [ipaddress.IPv6Address(unicode('0::0')), ipaddress.IPv6Address(unicode('0::1'))]
NameError: name 'unicode' is not defined
root@qa-eth-vt03-1-4600ca1:/home/admin#
```

#### New command output (if the output of a command-line utility has changed)
```
root@r-panther-13:/home/admin# config radius nasip 1.1.1.1
root@r-panther-13:/home/admin# config radius sourceip 1.1.1.1
root@r-panther-13:/home/admin# show radius 
RADIUS global auth_type pap (default)
RADIUS global retransmit 3 (default)
RADIUS global timeout 5 (default)
RADIUS global passkey <EMPTY_STRING> (default)
RADIUS global nas_ip 1.1.1.1
RADIUS global src_ip 1.1.1.1

root@r-panther-13:/home/admin# 
```