[counters] skip showing counters that are not enabled (#2199)
What I did
Skip counters that are not enabled.

How to verify it
With change Azure/sonic-swss#2143, following commands will cause exception:

admin@vlab-01:~$ show priority-group persistent-watermark headroom
Traceback (most recent call last):
File "/usr/local/bin/watermarkstat", line 315, in
main()
File "/usr/local/bin/watermarkstat", line 310, in main
watermarkstat.print_all_stat(table_prefix, args.type)
File "/usr/local/bin/watermarkstat", line 261, in print_all_stat
data = self.get_counters(table_prefix,
File "/usr/local/bin/watermarkstat", line 237, in get_counters
elif fields[pos] != STATUS_NA:
IndexError: list index out of range

With the change:

admin@vlab-01:~$ show priority-group persistent-watermark headroom
Ingress headroom per PG:
Port
Ethernet0
Ethernet4
Ethernet8
Ethernet12
Ethernet16
... ...

Signed-off-by: Ying Xie ying.xie@microsoft.com