[show priority-group drop counters] Remove backup with cached PG drop counters after 'config reload' (#2386)
#### What I did
After config reload for some period of time when COUNTERS_PG_PORT_MAP is not created yet, CLI command 'show prioriy-group counter' exits with the traceback because it expects COUNTERS_PG_PORT_MAP to be present and doesn't do proper handling for the situation when it is not yet populated.
Handling was fixed

#### How I did it
use "not" instead of "is None"

#### How to verify it
UT added

#### Previous command output (if the output of a command-line utility has changed)
```
root@r-lionfish-13:/home/admin# show priority-group drop counters
Traceback (most recent call last):
  File "/usr/local/bin/pg-drop", line 262, in <module>
    main()
  File "/usr/local/bin/pg-drop", line 255, in main
    pgdropstat.print_all_stat(COUNTER_TABLE_PREFIX, "pg_drop" )
  File "/usr/local/bin/pg-drop", line 160, in print_all_stat
    self.build_header(type)
  File "/usr/local/bin/pg-drop", line 119, in build_header
    single_key = list(header_map.keys())[0]
IndexError: list index out of range

```

#### New command output (if the output of a command-line utility has changed)

`COUNTERS_PORT_NAME_MAP is empty!`